### ISSUE TITLE
Unsafe integer casts

### ISSUE THREAD

**Issue by phonologus** [phonologus/qed-new#1]
There are numerous places in the sourcecode where unsafe assumptions are made about the sizes of integers. It is a fair bit of work tracking all of these down, but I expect to fix many of them in the next few commits. The latest commit already contains a number of fixes.

**Comment by phonologus** [comment]
I've introduced a new type `ldesc` to represent line descriptors. These were originally represented as an `int` cookie, with some bit twiddling and masking voodoo to access the file offset and flag that the `int` encoded. This had a knock-on effect in how the tempfile blocks were structured, and how big the tempfile could be. As these blocks needed to be on 4-byte boundaries, this added further complexity to the in-memory buffering.

By separating the file offset and the flag into separate fields in a `struct`, the block algorithm is simplified, the artificial limits on the size of the tempfile are removed, and the Qed (line) addressing logic is made explicit throughout the sourcecode..

This has resulted in an easier to debug, and (hopefully) more robust tempfile buffering implementation.

With these changes now in place, I will close this issue.

**Comment by aksr** [comment]
It seems already more stable. I'll test it in following days. Thank you!
